// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See VmyCPU.h for the primary calling header

#include "verilated.h"
#include "verilated_dpi.h"

#include "VmyCPU_Cache.h"

VL_ATTR_COLD void VmyCPU_Cache___ctor_var_reset(VmyCPU_Cache* vlSelf) {
    if (false && vlSelf) {}  // Prevent unused
    VmyCPU__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+        VmyCPU_Cache___ctor_var_reset\n"); );
    // Body
    vlSelf->clock = VL_RAND_RESET_I(1);
    vlSelf->reset = VL_RAND_RESET_I(1);
    vlSelf->io_cpu_request_addr = VL_RAND_RESET_I(32);
    vlSelf->io_cpu_request_data = VL_RAND_RESET_Q(64);
    vlSelf->io_cpu_request_mask = VL_RAND_RESET_I(8);
    vlSelf->io_cpu_request_rw = VL_RAND_RESET_I(1);
    vlSelf->io_cpu_request_valid = VL_RAND_RESET_I(1);
    vlSelf->io_cpu_response_data = VL_RAND_RESET_Q(64);
    vlSelf->io_cpu_response_ready = VL_RAND_RESET_I(1);
    vlSelf->io_mem_io_aw_ready = VL_RAND_RESET_I(1);
    vlSelf->io_mem_io_aw_valid = VL_RAND_RESET_I(1);
    vlSelf->io_mem_io_aw_bits_addr = VL_RAND_RESET_I(32);
    vlSelf->io_mem_io_aw_bits_len = VL_RAND_RESET_I(8);
    vlSelf->io_mem_io_w_ready = VL_RAND_RESET_I(1);
    vlSelf->io_mem_io_w_valid = VL_RAND_RESET_I(1);
    vlSelf->io_mem_io_w_bits_data = VL_RAND_RESET_Q(64);
    vlSelf->io_mem_io_w_bits_strb = VL_RAND_RESET_I(8);
    vlSelf->io_mem_io_w_bits_last = VL_RAND_RESET_I(1);
    vlSelf->io_mem_io_b_ready = VL_RAND_RESET_I(1);
    vlSelf->io_mem_io_b_valid = VL_RAND_RESET_I(1);
    vlSelf->io_mem_io_ar_ready = VL_RAND_RESET_I(1);
    vlSelf->io_mem_io_ar_valid = VL_RAND_RESET_I(1);
    vlSelf->io_mem_io_ar_bits_addr = VL_RAND_RESET_I(32);
    vlSelf->io_mem_io_ar_bits_len = VL_RAND_RESET_I(8);
    vlSelf->io_mem_io_r_ready = VL_RAND_RESET_I(1);
    vlSelf->io_mem_io_r_valid = VL_RAND_RESET_I(1);
    vlSelf->io_mem_io_r_bits_data = VL_RAND_RESET_Q(64);
    vlSelf->io_mem_io_r_bits_last = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_0_io_cache_req_we = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_0_io_tag_write_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_0_io_tag_write_dirty = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_0_io_tag_write_visit = VL_RAND_RESET_I(8);
    vlSelf->__PVT__tag_mem_0_io_tag_write_tag = VL_RAND_RESET_I(22);
    vlSelf->__PVT__tag_mem_0_io_tag_read_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_0_io_tag_read_dirty = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_0_io_tag_read_visit = VL_RAND_RESET_I(8);
    vlSelf->__PVT__tag_mem_0_io_tag_read_tag = VL_RAND_RESET_I(22);
    vlSelf->__PVT__tag_mem_1_io_cache_req_we = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_1_io_tag_write_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_1_io_tag_write_dirty = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_1_io_tag_write_visit = VL_RAND_RESET_I(8);
    vlSelf->__PVT__tag_mem_1_io_tag_write_tag = VL_RAND_RESET_I(22);
    vlSelf->__PVT__tag_mem_1_io_tag_read_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_1_io_tag_read_dirty = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_1_io_tag_read_visit = VL_RAND_RESET_I(8);
    vlSelf->__PVT__tag_mem_1_io_tag_read_tag = VL_RAND_RESET_I(22);
    vlSelf->__PVT__tag_mem_2_io_cache_req_we = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_2_io_tag_write_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_2_io_tag_write_dirty = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_2_io_tag_write_visit = VL_RAND_RESET_I(8);
    vlSelf->__PVT__tag_mem_2_io_tag_write_tag = VL_RAND_RESET_I(22);
    vlSelf->__PVT__tag_mem_2_io_tag_read_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_2_io_tag_read_dirty = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_2_io_tag_read_visit = VL_RAND_RESET_I(8);
    vlSelf->__PVT__tag_mem_2_io_tag_read_tag = VL_RAND_RESET_I(22);
    vlSelf->__PVT__tag_mem_3_io_cache_req_we = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_3_io_tag_write_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_3_io_tag_write_dirty = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_3_io_tag_write_visit = VL_RAND_RESET_I(8);
    vlSelf->__PVT__tag_mem_3_io_tag_write_tag = VL_RAND_RESET_I(22);
    vlSelf->__PVT__tag_mem_3_io_tag_read_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_3_io_tag_read_dirty = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_3_io_tag_read_visit = VL_RAND_RESET_I(8);
    vlSelf->__PVT__tag_mem_3_io_tag_read_tag = VL_RAND_RESET_I(22);
    vlSelf->__PVT__data_mem_0_io_cache_req_we = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(1024, vlSelf->__PVT__data_mem_0_io_data_write_data);
    VL_RAND_RESET_W(1024, vlSelf->__PVT__data_mem_0_io_data_read_data);
    vlSelf->__PVT__data_mem_1_io_cache_req_we = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(1024, vlSelf->__PVT__data_mem_1_io_data_write_data);
    VL_RAND_RESET_W(1024, vlSelf->__PVT__data_mem_1_io_data_read_data);
    vlSelf->__PVT__data_mem_2_io_cache_req_we = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(1024, vlSelf->__PVT__data_mem_2_io_data_write_data);
    VL_RAND_RESET_W(1024, vlSelf->__PVT__data_mem_2_io_data_read_data);
    vlSelf->__PVT__data_mem_3_io_cache_req_we = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(1024, vlSelf->__PVT__data_mem_3_io_data_write_data);
    VL_RAND_RESET_W(1024, vlSelf->__PVT__data_mem_3_io_data_read_data);
    vlSelf->__PVT__cache_state = VL_RAND_RESET_I(4);
    vlSelf->__PVT__index = VL_RAND_RESET_I(4);
    vlSelf->__PVT__fill_block_en = VL_RAND_RESET_I(1);
    vlSelf->__PVT___GEN_0 = VL_RAND_RESET_I(4);
    vlSelf->__PVT__last = VL_RAND_RESET_I(1);
    vlSelf->__PVT__replace = VL_RAND_RESET_I(2);
    vlSelf->__PVT__refill_addr = VL_RAND_RESET_I(32);
    vlSelf->__PVT__writeback_addr = VL_RAND_RESET_I(32);
    vlSelf->__PVT__cpu_request_addr_reg = VL_RAND_RESET_I(32);
    vlSelf->__PVT__cpu_request_data = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__cpu_request_mask = VL_RAND_RESET_I(8);
    vlSelf->__PVT__cpu_request_rw = VL_RAND_RESET_I(1);
    vlSelf->__PVT__is_match_0 = VL_RAND_RESET_I(1);
    vlSelf->__PVT__is_match_1 = VL_RAND_RESET_I(1);
    vlSelf->__PVT__is_match_2 = VL_RAND_RESET_I(1);
    vlSelf->__PVT__is_match_3 = VL_RAND_RESET_I(1);
    vlSelf->__PVT___io_cpu_response_data_T_70 = VL_RAND_RESET_Q(64);
    VL_RAND_RESET_W(1024, vlSelf->__PVT__response_data);
    vlSelf->__PVT___part_0_T_22 = VL_RAND_RESET_I(8);
    vlSelf->__PVT___part_1_T_22 = VL_RAND_RESET_I(16);
    vlSelf->__PVT___part_2_T_22 = VL_RAND_RESET_I(24);
    vlSelf->__PVT___part_3_T_22 = VL_RAND_RESET_I(32);
    vlSelf->__PVT___part_4_T_22 = VL_RAND_RESET_Q(40);
    vlSelf->__PVT___part_5_T_22 = VL_RAND_RESET_Q(48);
    vlSelf->__PVT___part_6_T_22 = VL_RAND_RESET_Q(56);
    vlSelf->__PVT___part_7_T_22 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__result = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__cache_data_1 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__cache_data_0 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__cache_data_3 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__cache_data_2 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__cache_data_5 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__cache_data_4 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__cache_data_7 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__cache_data_6 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__cache_data_9 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__cache_data_8 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__cache_data_11 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__cache_data_10 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__cache_data_13 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__cache_data_12 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__cache_data_15 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__cache_data_14 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT__visit_1 = VL_RAND_RESET_I(8);
    vlSelf->__PVT__visit_0 = VL_RAND_RESET_I(8);
    vlSelf->__PVT__visit_3 = VL_RAND_RESET_I(8);
    vlSelf->__PVT__visit_2 = VL_RAND_RESET_I(8);
    vlSelf->__PVT__compare_2_3 = VL_RAND_RESET_I(1);
    vlSelf->__PVT__compare_1_0 = VL_RAND_RESET_I(1);
    vlSelf->__PVT__max_01_or_23 = VL_RAND_RESET_I(1);
    vlSelf->__PVT__max = VL_RAND_RESET_I(2);
    vlSelf->__PVT___GEN_1143 = VL_RAND_RESET_Q(64);
    vlSelf->__PVT___GEN_1593 = VL_RAND_RESET_I(4);
    vlSelf->__PVT___GEN_1663 = VL_RAND_RESET_I(2);
    vlSelf->__PVT___GEN_1664 = VL_RAND_RESET_I(32);
    vlSelf->__PVT___GEN_1665 = VL_RAND_RESET_I(32);
    vlSelf->__PVT___GEN_1671 = VL_RAND_RESET_I(4);
    vlSelf->__PVT__tag_mem_0__DOT__tag_mem_0_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_0__DOT__tag_mem_0_dirty = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_0__DOT__tag_mem_0_visit = VL_RAND_RESET_I(8);
    vlSelf->__PVT__tag_mem_0__DOT__tag_mem_0_tag = VL_RAND_RESET_I(22);
    vlSelf->__PVT__tag_mem_0__DOT__tag_mem_1_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_0__DOT__tag_mem_1_dirty = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_0__DOT__tag_mem_1_visit = VL_RAND_RESET_I(8);
    vlSelf->__PVT__tag_mem_0__DOT__tag_mem_1_tag = VL_RAND_RESET_I(22);
    vlSelf->__PVT__tag_mem_0__DOT__tag_mem_2_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_0__DOT__tag_mem_2_dirty = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_0__DOT__tag_mem_2_visit = VL_RAND_RESET_I(8);
    vlSelf->__PVT__tag_mem_0__DOT__tag_mem_2_tag = VL_RAND_RESET_I(22);
    vlSelf->__PVT__tag_mem_0__DOT__tag_mem_3_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_0__DOT__tag_mem_3_dirty = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_0__DOT__tag_mem_3_visit = VL_RAND_RESET_I(8);
    vlSelf->__PVT__tag_mem_0__DOT__tag_mem_3_tag = VL_RAND_RESET_I(22);
    vlSelf->__PVT__tag_mem_0__DOT__tag_mem_4_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_0__DOT__tag_mem_4_dirty = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_0__DOT__tag_mem_4_visit = VL_RAND_RESET_I(8);
    vlSelf->__PVT__tag_mem_0__DOT__tag_mem_4_tag = VL_RAND_RESET_I(22);
    vlSelf->__PVT__tag_mem_0__DOT__tag_mem_5_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_0__DOT__tag_mem_5_dirty = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_0__DOT__tag_mem_5_visit = VL_RAND_RESET_I(8);
    vlSelf->__PVT__tag_mem_0__DOT__tag_mem_5_tag = VL_RAND_RESET_I(22);
    vlSelf->__PVT__tag_mem_0__DOT__tag_mem_6_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_0__DOT__tag_mem_6_dirty = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_0__DOT__tag_mem_6_visit = VL_RAND_RESET_I(8);
    vlSelf->__PVT__tag_mem_0__DOT__tag_mem_6_tag = VL_RAND_RESET_I(22);
    vlSelf->__PVT__tag_mem_0__DOT__tag_mem_7_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_0__DOT__tag_mem_7_dirty = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_0__DOT__tag_mem_7_visit = VL_RAND_RESET_I(8);
    vlSelf->__PVT__tag_mem_0__DOT__tag_mem_7_tag = VL_RAND_RESET_I(22);
    vlSelf->__PVT__tag_mem_1__DOT__tag_mem_0_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_1__DOT__tag_mem_0_dirty = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_1__DOT__tag_mem_0_visit = VL_RAND_RESET_I(8);
    vlSelf->__PVT__tag_mem_1__DOT__tag_mem_0_tag = VL_RAND_RESET_I(22);
    vlSelf->__PVT__tag_mem_1__DOT__tag_mem_1_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_1__DOT__tag_mem_1_dirty = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_1__DOT__tag_mem_1_visit = VL_RAND_RESET_I(8);
    vlSelf->__PVT__tag_mem_1__DOT__tag_mem_1_tag = VL_RAND_RESET_I(22);
    vlSelf->__PVT__tag_mem_1__DOT__tag_mem_2_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_1__DOT__tag_mem_2_dirty = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_1__DOT__tag_mem_2_visit = VL_RAND_RESET_I(8);
    vlSelf->__PVT__tag_mem_1__DOT__tag_mem_2_tag = VL_RAND_RESET_I(22);
    vlSelf->__PVT__tag_mem_1__DOT__tag_mem_3_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_1__DOT__tag_mem_3_dirty = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_1__DOT__tag_mem_3_visit = VL_RAND_RESET_I(8);
    vlSelf->__PVT__tag_mem_1__DOT__tag_mem_3_tag = VL_RAND_RESET_I(22);
    vlSelf->__PVT__tag_mem_1__DOT__tag_mem_4_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_1__DOT__tag_mem_4_dirty = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_1__DOT__tag_mem_4_visit = VL_RAND_RESET_I(8);
    vlSelf->__PVT__tag_mem_1__DOT__tag_mem_4_tag = VL_RAND_RESET_I(22);
    vlSelf->__PVT__tag_mem_1__DOT__tag_mem_5_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_1__DOT__tag_mem_5_dirty = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_1__DOT__tag_mem_5_visit = VL_RAND_RESET_I(8);
    vlSelf->__PVT__tag_mem_1__DOT__tag_mem_5_tag = VL_RAND_RESET_I(22);
    vlSelf->__PVT__tag_mem_1__DOT__tag_mem_6_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_1__DOT__tag_mem_6_dirty = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_1__DOT__tag_mem_6_visit = VL_RAND_RESET_I(8);
    vlSelf->__PVT__tag_mem_1__DOT__tag_mem_6_tag = VL_RAND_RESET_I(22);
    vlSelf->__PVT__tag_mem_1__DOT__tag_mem_7_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_1__DOT__tag_mem_7_dirty = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_1__DOT__tag_mem_7_visit = VL_RAND_RESET_I(8);
    vlSelf->__PVT__tag_mem_1__DOT__tag_mem_7_tag = VL_RAND_RESET_I(22);
    vlSelf->__PVT__tag_mem_2__DOT__tag_mem_0_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_2__DOT__tag_mem_0_dirty = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_2__DOT__tag_mem_0_visit = VL_RAND_RESET_I(8);
    vlSelf->__PVT__tag_mem_2__DOT__tag_mem_0_tag = VL_RAND_RESET_I(22);
    vlSelf->__PVT__tag_mem_2__DOT__tag_mem_1_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_2__DOT__tag_mem_1_dirty = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_2__DOT__tag_mem_1_visit = VL_RAND_RESET_I(8);
    vlSelf->__PVT__tag_mem_2__DOT__tag_mem_1_tag = VL_RAND_RESET_I(22);
    vlSelf->__PVT__tag_mem_2__DOT__tag_mem_2_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_2__DOT__tag_mem_2_dirty = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_2__DOT__tag_mem_2_visit = VL_RAND_RESET_I(8);
    vlSelf->__PVT__tag_mem_2__DOT__tag_mem_2_tag = VL_RAND_RESET_I(22);
    vlSelf->__PVT__tag_mem_2__DOT__tag_mem_3_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_2__DOT__tag_mem_3_dirty = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_2__DOT__tag_mem_3_visit = VL_RAND_RESET_I(8);
    vlSelf->__PVT__tag_mem_2__DOT__tag_mem_3_tag = VL_RAND_RESET_I(22);
    vlSelf->__PVT__tag_mem_2__DOT__tag_mem_4_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_2__DOT__tag_mem_4_dirty = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_2__DOT__tag_mem_4_visit = VL_RAND_RESET_I(8);
    vlSelf->__PVT__tag_mem_2__DOT__tag_mem_4_tag = VL_RAND_RESET_I(22);
    vlSelf->__PVT__tag_mem_2__DOT__tag_mem_5_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_2__DOT__tag_mem_5_dirty = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_2__DOT__tag_mem_5_visit = VL_RAND_RESET_I(8);
    vlSelf->__PVT__tag_mem_2__DOT__tag_mem_5_tag = VL_RAND_RESET_I(22);
    vlSelf->__PVT__tag_mem_2__DOT__tag_mem_6_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_2__DOT__tag_mem_6_dirty = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_2__DOT__tag_mem_6_visit = VL_RAND_RESET_I(8);
    vlSelf->__PVT__tag_mem_2__DOT__tag_mem_6_tag = VL_RAND_RESET_I(22);
    vlSelf->__PVT__tag_mem_2__DOT__tag_mem_7_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_2__DOT__tag_mem_7_dirty = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_2__DOT__tag_mem_7_visit = VL_RAND_RESET_I(8);
    vlSelf->__PVT__tag_mem_2__DOT__tag_mem_7_tag = VL_RAND_RESET_I(22);
    vlSelf->__PVT__tag_mem_3__DOT__tag_mem_0_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_3__DOT__tag_mem_0_dirty = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_3__DOT__tag_mem_0_visit = VL_RAND_RESET_I(8);
    vlSelf->__PVT__tag_mem_3__DOT__tag_mem_0_tag = VL_RAND_RESET_I(22);
    vlSelf->__PVT__tag_mem_3__DOT__tag_mem_1_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_3__DOT__tag_mem_1_dirty = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_3__DOT__tag_mem_1_visit = VL_RAND_RESET_I(8);
    vlSelf->__PVT__tag_mem_3__DOT__tag_mem_1_tag = VL_RAND_RESET_I(22);
    vlSelf->__PVT__tag_mem_3__DOT__tag_mem_2_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_3__DOT__tag_mem_2_dirty = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_3__DOT__tag_mem_2_visit = VL_RAND_RESET_I(8);
    vlSelf->__PVT__tag_mem_3__DOT__tag_mem_2_tag = VL_RAND_RESET_I(22);
    vlSelf->__PVT__tag_mem_3__DOT__tag_mem_3_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_3__DOT__tag_mem_3_dirty = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_3__DOT__tag_mem_3_visit = VL_RAND_RESET_I(8);
    vlSelf->__PVT__tag_mem_3__DOT__tag_mem_3_tag = VL_RAND_RESET_I(22);
    vlSelf->__PVT__tag_mem_3__DOT__tag_mem_4_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_3__DOT__tag_mem_4_dirty = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_3__DOT__tag_mem_4_visit = VL_RAND_RESET_I(8);
    vlSelf->__PVT__tag_mem_3__DOT__tag_mem_4_tag = VL_RAND_RESET_I(22);
    vlSelf->__PVT__tag_mem_3__DOT__tag_mem_5_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_3__DOT__tag_mem_5_dirty = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_3__DOT__tag_mem_5_visit = VL_RAND_RESET_I(8);
    vlSelf->__PVT__tag_mem_3__DOT__tag_mem_5_tag = VL_RAND_RESET_I(22);
    vlSelf->__PVT__tag_mem_3__DOT__tag_mem_6_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_3__DOT__tag_mem_6_dirty = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_3__DOT__tag_mem_6_visit = VL_RAND_RESET_I(8);
    vlSelf->__PVT__tag_mem_3__DOT__tag_mem_6_tag = VL_RAND_RESET_I(22);
    vlSelf->__PVT__tag_mem_3__DOT__tag_mem_7_valid = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_3__DOT__tag_mem_7_dirty = VL_RAND_RESET_I(1);
    vlSelf->__PVT__tag_mem_3__DOT__tag_mem_7_visit = VL_RAND_RESET_I(8);
    vlSelf->__PVT__tag_mem_3__DOT__tag_mem_7_tag = VL_RAND_RESET_I(22);
    for (int __Vi0=0; __Vi0<8; ++__Vi0) {
        VL_RAND_RESET_W(1024, vlSelf->__PVT__data_mem_0__DOT__data_mem_data[__Vi0]);
    }
    vlSelf->__PVT__data_mem_0__DOT__data_mem_data_readData_en_pipe_0 = VL_RAND_RESET_I(1);
    vlSelf->__PVT__data_mem_0__DOT__data_mem_data_readData_addr_pipe_0 = VL_RAND_RESET_I(3);
    VL_RAND_RESET_W(1024, vlSelf->__PVT__data_mem_0__DOT__wDataReg_data);
    vlSelf->__PVT__data_mem_0__DOT__doForwardReg = VL_RAND_RESET_I(1);
    for (int __Vi0=0; __Vi0<8; ++__Vi0) {
        VL_RAND_RESET_W(1024, vlSelf->__PVT__data_mem_1__DOT__data_mem_data[__Vi0]);
    }
    vlSelf->__PVT__data_mem_1__DOT__data_mem_data_readData_en_pipe_0 = VL_RAND_RESET_I(1);
    vlSelf->__PVT__data_mem_1__DOT__data_mem_data_readData_addr_pipe_0 = VL_RAND_RESET_I(3);
    VL_RAND_RESET_W(1024, vlSelf->__PVT__data_mem_1__DOT__wDataReg_data);
    vlSelf->__PVT__data_mem_1__DOT__doForwardReg = VL_RAND_RESET_I(1);
    for (int __Vi0=0; __Vi0<8; ++__Vi0) {
        VL_RAND_RESET_W(1024, vlSelf->__PVT__data_mem_2__DOT__data_mem_data[__Vi0]);
    }
    vlSelf->__PVT__data_mem_2__DOT__data_mem_data_readData_en_pipe_0 = VL_RAND_RESET_I(1);
    vlSelf->__PVT__data_mem_2__DOT__data_mem_data_readData_addr_pipe_0 = VL_RAND_RESET_I(3);
    VL_RAND_RESET_W(1024, vlSelf->__PVT__data_mem_2__DOT__wDataReg_data);
    vlSelf->__PVT__data_mem_2__DOT__doForwardReg = VL_RAND_RESET_I(1);
    for (int __Vi0=0; __Vi0<8; ++__Vi0) {
        VL_RAND_RESET_W(1024, vlSelf->__PVT__data_mem_3__DOT__data_mem_data[__Vi0]);
    }
    vlSelf->__PVT__data_mem_3__DOT__data_mem_data_readData_en_pipe_0 = VL_RAND_RESET_I(1);
    vlSelf->__PVT__data_mem_3__DOT__data_mem_data_readData_addr_pipe_0 = VL_RAND_RESET_I(3);
    VL_RAND_RESET_W(1024, vlSelf->__PVT__data_mem_3__DOT__wDataReg_data);
    vlSelf->__PVT__data_mem_3__DOT__doForwardReg = VL_RAND_RESET_I(1);
}
