// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See VmyCPU.h for the primary calling header

#ifndef VERILATED_VMYCPU___024ROOT_H_
#define VERILATED_VMYCPU___024ROOT_H_  // guard

#include "verilated.h"

class VmyCPU__Syms;
class VmyCPU___024unit;
class VmyCPU_Cache;

VL_MODULE(VmyCPU___024root) {
  public:
    // CELLS
    VmyCPU___024unit* __PVT____024unit;
    VmyCPU_Cache* __PVT__myCPU__DOT__icache;
    VmyCPU_Cache* __PVT__myCPU__DOT__dcache;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clock,0,0);
        VL_IN8(reset,0,0);
        VL_OUT8(io_start,0,0);
        VL_OUT8(io_stall,0,0);
        VL_IN8(io_master_awready,0,0);
        VL_OUT8(io_master_awvalid,0,0);
        VL_OUT8(io_master_awid,3,0);
        VL_OUT8(io_master_awlen,7,0);
        VL_OUT8(io_master_awsize,2,0);
        VL_OUT8(io_master_awburst,1,0);
        VL_IN8(io_master_wready,0,0);
        VL_OUT8(io_master_wvalid,0,0);
        VL_OUT8(io_master_wstrb,7,0);
        VL_OUT8(io_master_wlast,0,0);
        VL_OUT8(io_master_bready,0,0);
        VL_IN8(io_master_bvalid,0,0);
        VL_IN8(io_master_bresp,1,0);
        VL_IN8(io_master_bid,3,0);
        VL_IN8(io_master_arready,0,0);
        VL_OUT8(io_master_arvalid,0,0);
        VL_OUT8(io_master_arid,3,0);
        VL_OUT8(io_master_arlen,7,0);
        VL_OUT8(io_master_arsize,2,0);
        VL_OUT8(io_master_arburst,1,0);
        VL_OUT8(io_master_rready,0,0);
        VL_IN8(io_master_rvalid,0,0);
        VL_IN8(io_master_rresp,1,0);
        VL_IN8(io_master_rlast,0,0);
        VL_IN8(io_master_rid,3,0);
        CData/*0:0*/ myCPU__DOT__datapath_io_dcache_cpu_request_rw;
        CData/*0:0*/ myCPU__DOT__datapath_io_dcache_cpu_request_valid;
        CData/*2:0*/ myCPU__DOT__control_io_imm_sel;
        CData/*2:0*/ myCPU__DOT__control_io_csr_cmd;
        CData/*0:0*/ myCPU__DOT__arb_io_icache_ar_ready;
        CData/*0:0*/ myCPU__DOT__arb_io_icache_r_valid;
        CData/*0:0*/ myCPU__DOT__arb_io_dcache_aw_ready;
        CData/*0:0*/ myCPU__DOT__arb_io_dcache_w_ready;
        CData/*0:0*/ myCPU__DOT__arb_io_dcache_b_valid;
        CData/*0:0*/ myCPU__DOT__arb_io_dcache_ar_ready;
        CData/*0:0*/ myCPU__DOT__arb_io_dcache_r_valid;
        CData/*0:0*/ myCPU__DOT__arb_io_axi_out_b_ready;
        CData/*0:0*/ myCPU__DOT__arb_io_axi_out_r_ready;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__regFile_io_wen;
        CData/*3:0*/ myCPU__DOT__datapath__DOT__csr_io_flush_mask;
        CData/*2:0*/ myCPU__DOT__datapath__DOT__csr_io_r_op;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__csr_io_load_misalign;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__csr_io_store_misalign;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__csr_io_trap;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__fd_pipe_reg_enable;
        CData/*3:0*/ myCPU__DOT__datapath__DOT__de_pipe_reg_alu_op;
        CData/*2:0*/ myCPU__DOT__datapath__DOT__de_pipe_reg_csr_write_op;
        CData/*4:0*/ myCPU__DOT__datapath__DOT__de_pipe_reg_dest;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__de_pipe_reg_A_sel;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__de_pipe_reg_B_sel;
        CData/*1:0*/ myCPU__DOT__datapath__DOT__de_pipe_reg_pc_sel;
        CData/*2:0*/ myCPU__DOT__datapath__DOT__de_pipe_reg_br_type;
        CData/*1:0*/ myCPU__DOT__datapath__DOT__de_pipe_reg_wd_type;
        CData/*2:0*/ myCPU__DOT__datapath__DOT__de_pipe_reg_st_type;
        CData/*2:0*/ myCPU__DOT__datapath__DOT__de_pipe_reg_ld_type;
        CData/*1:0*/ myCPU__DOT__datapath__DOT__de_pipe_reg_wb_sel;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__de_pipe_reg_wb_en;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__de_pipe_reg_enable;
        CData/*2:0*/ myCPU__DOT__datapath__DOT__em_pipe_reg_csr_write_op;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__em_pipe_reg_jump_taken;
    };
    struct {
        CData/*2:0*/ myCPU__DOT__datapath__DOT__em_pipe_reg_st_type;
        CData/*2:0*/ myCPU__DOT__datapath__DOT__em_pipe_reg_ld_type;
        CData/*1:0*/ myCPU__DOT__datapath__DOT__em_pipe_reg_wb_sel;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__em_pipe_reg_wb_en;
        CData/*4:0*/ myCPU__DOT__datapath__DOT__em_pipe_reg_dest;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__em_pipe_reg_enable;
        CData/*4:0*/ myCPU__DOT__datapath__DOT__mw_pipe_reg_dest;
        CData/*2:0*/ myCPU__DOT__datapath__DOT__mw_pipe_reg_csr_write_op;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__mw_pipe_reg_jump_taken;
        CData/*1:0*/ myCPU__DOT__datapath__DOT__mw_pipe_reg_wb_sel;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__mw_pipe_reg_wb_en;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__mw_pipe_reg_enable;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__started;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__dcache_stall;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__stall;
        CData/*3:0*/ myCPU__DOT__datapath__DOT__csr_atomic_flush;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__brCond_taken;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__jmp_occur;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__flush_fd;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__flush_de;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__flush_em;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__flush_mw;
        CData/*0:0*/ myCPU__DOT__datapath__DOT___next_pc_T_5;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__is_kill_inst;
        CData/*0:0*/ myCPU__DOT__datapath__DOT___GEN_2;
        CData/*0:0*/ myCPU__DOT__datapath__DOT___csr_op_T_2;
        CData/*2:0*/ myCPU__DOT__datapath__DOT___csr_op_T_16;
        CData/*0:0*/ myCPU__DOT__datapath__DOT___T_6;
        CData/*7:0*/ myCPU__DOT__datapath__DOT__st_mask;
        CData/*5:0*/ myCPU__DOT__datapath__DOT__alu__DOT__shamt;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__brCond__DOT__eq;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__brCond__DOT__lt;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__brCond__DOT__ltu;
        CData/*1:0*/ myCPU__DOT__datapath__DOT__csr__DOT__mode;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__csr__DOT__mstatus_sum;
        CData/*1:0*/ myCPU__DOT__datapath__DOT__csr__DOT__mstatus_mpp;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__csr__DOT__mstatus_spp;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__csr__DOT__mstatus_mpie;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__csr__DOT__mstatus_spie;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__csr__DOT__mstatus_mie;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__csr__DOT__mstatus_sie;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__csr__DOT__mie_meie;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__csr__DOT__mie_seie;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__csr__DOT__mie_mtie;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__csr__DOT__mie_stie;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__csr__DOT__mie_msie;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__csr__DOT__mie_ssie;
        CData/*1:0*/ myCPU__DOT__datapath__DOT__csr__DOT__mtvec_mode;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__csr__DOT__mcause_int;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__csr__DOT__mip_meip;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__csr__DOT__mip_seip;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__csr__DOT__mip_stip;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__csr__DOT__mip_msip;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__csr__DOT__mip_ssip;
        CData/*1:0*/ myCPU__DOT__datapath__DOT__csr__DOT__stvec_mode;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__csr__DOT__scause_int;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__csr__DOT__readable;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__csr__DOT___T_144;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__csr__DOT__writable;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__csr__DOT___instValid_T;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__csr__DOT__valid;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__csr__DOT__writeEn;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__csr__DOT__hasIntM;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__csr__DOT__hasInt;
    };
    struct {
        CData/*0:0*/ myCPU__DOT__datapath__DOT__csr__DOT__handIntS;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__csr__DOT__hasExc;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__csr__DOT__handExcS;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__csr__DOT___GEN_66;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__csr__DOT___GEN_67;
        CData/*1:0*/ myCPU__DOT__datapath__DOT__csr__DOT___GEN_68;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__csr__DOT___GEN_70;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__csr__DOT___GEN_74;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__csr__DOT___GEN_75;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__csr__DOT___GEN_77;
        CData/*0:0*/ myCPU__DOT__datapath__DOT__csr__DOT___GEN_81;
        CData/*1:0*/ myCPU__DOT__control__DOT___ctrlSignals_T_154;
        CData/*1:0*/ myCPU__DOT__control__DOT___ctrlSignals_T_169;
        CData/*1:0*/ myCPU__DOT__control__DOT___ctrlSignals_T_184;
        CData/*1:0*/ myCPU__DOT__control__DOT___ctrlSignals_T_199;
        CData/*0:0*/ myCPU__DOT__control__DOT___ctrlSignals_T_243;
        CData/*0:0*/ myCPU__DOT__control__DOT___ctrlSignals_T_265;
        CData/*0:0*/ myCPU__DOT__control__DOT___ctrlSignals_T_309;
        CData/*0:0*/ myCPU__DOT__control__DOT___ctrlSignals_T_326;
        CData/*1:0*/ myCPU__DOT__control__DOT___ctrlSignals_T_366;
        CData/*1:0*/ myCPU__DOT__control__DOT___ctrlSignals_T_381;
        CData/*1:0*/ myCPU__DOT__control__DOT___ctrlSignals_T_396;
        CData/*2:0*/ myCPU__DOT__control__DOT___ctrlSignals_T_425;
        CData/*2:0*/ myCPU__DOT__control__DOT___ctrlSignals_T_440;
        CData/*2:0*/ myCPU__DOT__control__DOT___ctrlSignals_T_455;
        CData/*2:0*/ myCPU__DOT__control__DOT___ctrlSignals_T_470;
        CData/*4:0*/ myCPU__DOT__control__DOT___ctrlSignals_T_493;
        CData/*4:0*/ myCPU__DOT__control__DOT___ctrlSignals_T_508;
        CData/*4:0*/ myCPU__DOT__control__DOT___ctrlSignals_T_523;
        CData/*4:0*/ myCPU__DOT__control__DOT___ctrlSignals_T_538;
        CData/*2:0*/ myCPU__DOT__control__DOT___ctrlSignals_T_676;
        CData/*2:0*/ myCPU__DOT__control__DOT___ctrlSignals_T_748;
        CData/*1:0*/ myCPU__DOT__control__DOT___ctrlSignals_T_765;
        CData/*1:0*/ myCPU__DOT__control__DOT___ctrlSignals_T_780;
        CData/*1:0*/ myCPU__DOT__control__DOT___ctrlSignals_T_795;
        CData/*1:0*/ myCPU__DOT__control__DOT___ctrlSignals_T_810;
        CData/*0:0*/ myCPU__DOT__control__DOT___ctrlSignals_T_821;
        CData/*0:0*/ myCPU__DOT__control__DOT___ctrlSignals_T_851;
        CData/*0:0*/ myCPU__DOT__control__DOT___ctrlSignals_T_868;
        CData/*1:0*/ myCPU__DOT__control__DOT___ctrlSignals_T_902;
        CData/*1:0*/ myCPU__DOT__control__DOT___ctrlSignals_T_917;
        CData/*1:0*/ myCPU__DOT__control__DOT___ctrlSignals_T_932;
        CData/*1:0*/ myCPU__DOT__control__DOT___ctrlSignals_T_947;
        CData/*2:0*/ myCPU__DOT__control__DOT___ctrlSignals_T_972;
        CData/*2:0*/ myCPU__DOT__control__DOT___ctrlSignals_T_987;
        CData/*2:0*/ myCPU__DOT__control__DOT___ctrlSignals_T_1002;
        CData/*2:0*/ myCPU__DOT__control__DOT___ctrlSignals_T_1017;
        CData/*0:0*/ myCPU__DOT__control__DOT___ctrlSignals_T_1042;
        CData/*0:0*/ myCPU__DOT__control__DOT___ctrlSignals_T_1059;
        CData/*0:0*/ myCPU__DOT__control__DOT___ctrlSignals_T_1076;
        CData/*0:0*/ myCPU__DOT__control__DOT___ctrlSignals_T_1109;
        CData/*0:0*/ myCPU__DOT__control__DOT___ctrlSignals_T_1126;
        CData/*0:0*/ myCPU__DOT__control__DOT___ctrlSignals_T_1143;
        CData/*2:0*/ myCPU__DOT__arb__DOT__state;
        CData/*2:0*/ myCPU__DOT__arb__DOT___GEN_0;
        CData/*2:0*/ myCPU__DOT__arb__DOT___GEN_4;
        CData/*2:0*/ myCPU__DOT__arb__DOT___GEN_6;
        CData/*2:0*/ myCPU__DOT__arb__DOT___GEN_14;
        CData/*0:0*/ __Vclklast__TOP__clock;
        SData/*11:0*/ myCPU__DOT__datapath__DOT__de_pipe_reg_csr_write_addr;
        SData/*11:0*/ myCPU__DOT__datapath__DOT__em_pipe_reg_csr_write_addr;
        SData/*11:0*/ myCPU__DOT__datapath__DOT__mw_pipe_reg_csr_write_addr;
        VL_OUT(io_inst,31,0);
        VL_OUT(io_master_awaddr,31,0);
    };
    struct {
        VL_OUT(io_master_araddr,31,0);
        IData/*31:0*/ myCPU__DOT__datapath__DOT__csr_io_illegal_inst;
        IData/*31:0*/ myCPU__DOT__datapath__DOT__fd_pipe_reg_inst;
        IData/*31:0*/ myCPU__DOT__datapath__DOT__de_pipe_reg_inst;
        IData/*31:0*/ myCPU__DOT__datapath__DOT__em_pipe_reg_inst;
        IData/*31:0*/ myCPU__DOT__datapath__DOT__mw_pipe_reg_inst;
        VlWide<3>/*64:0*/ myCPU__DOT__datapath__DOT__pc;
        VlWide<3>/*64:0*/ myCPU__DOT__datapath__DOT___next_pc_T_11;
        IData/*31:0*/ myCPU__DOT__datapath__DOT___inst_T_7;
        VlWide<3>/*64:0*/ myCPU__DOT__datapath__DOT___io_icache_cpu_request_addr_T_2;
        VlWide<3>/*64:0*/ myCPU__DOT__datapath__DOT___GEN_136;
        VlWide<4>/*127:0*/ myCPU__DOT__datapath__DOT__alu__DOT___out_T_88;
        VL_OUT64(io_pc_debug,63,0);
        VL_OUT64(io_master_wdata,63,0);
        VL_IN64(io_master_rdata,63,0);
        QData/*63:0*/ myCPU__DOT__datapath__DOT__alu_io_A;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__alu_io_B;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__alu_io_out;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__alu_io_sum;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__brCond_io_rs1;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__brCond_io_rs2;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__regFile_io_wdata;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__regFile_io_rdata_1;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__csr_io_excValue;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__csr_io_trapVec;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__fd_pipe_reg_pc;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__de_pipe_reg_pc;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__de_pipe_reg_imm;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__de_pipe_reg_rs1;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__de_pipe_reg_src1_addr;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__de_pipe_reg_rs2;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__de_pipe_reg_src2_addr;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__de_pipe_reg_csr_read_data;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__de_pipe_reg_csr_write_data;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__em_pipe_reg_alu_out;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__em_pipe_reg_csr_read_data;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__em_pipe_reg_csr_write_data;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__em_pipe_reg_jump_addr;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__em_pipe_reg_st_data;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__em_pipe_reg_pc;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__mw_pipe_reg_load_data;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__mw_pipe_reg_alu_out;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__mw_pipe_reg_csr_read_data;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__mw_pipe_reg_csr_write_data;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__mw_pipe_reg_jump_addr;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__mw_pipe_reg_pc;
        QData/*63:0*/ myCPU__DOT__datapath__DOT___de_pipe_reg_rs1_T_11;
        QData/*63:0*/ myCPU__DOT__datapath__DOT___de_pipe_reg_rs1_T_12;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__load_data_hazard;
        QData/*63:0*/ myCPU__DOT__datapath__DOT___load_data_ext_hazard_T_5;
        QData/*63:0*/ myCPU__DOT__datapath__DOT___load_data_ext_hazard_T_34;
        QData/*63:0*/ myCPU__DOT__datapath__DOT___GEN_54;
        QData/*63:0*/ myCPU__DOT__datapath__DOT___GEN_56;
        QData/*63:0*/ myCPU__DOT__datapath__DOT___GEN_58;
        QData/*63:0*/ myCPU__DOT__datapath__DOT___GEN_60;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__A_data;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__B_data;
        QData/*63:0*/ myCPU__DOT__datapath__DOT___io_dcache_cpu_request_addr_T;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__alu__DOT__sum;
        QData/*43:0*/ myCPU__DOT__datapath__DOT__immGen__DOT__Iimm;
        QData/*52:0*/ myCPU__DOT__datapath__DOT__immGen__DOT__Jimm;
        QData/*43:0*/ myCPU__DOT__datapath__DOT__immGen__DOT___io_out_T_5;
        QData/*44:0*/ myCPU__DOT__datapath__DOT__immGen__DOT___io_out_T_7;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__regFile__DOT__reg_0;
    };
    struct {
        QData/*63:0*/ myCPU__DOT__datapath__DOT__regFile__DOT__reg_1;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__regFile__DOT__reg_2;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__regFile__DOT__reg_3;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__regFile__DOT__reg_4;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__regFile__DOT__reg_5;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__regFile__DOT__reg_6;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__regFile__DOT__reg_7;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__regFile__DOT__reg_8;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__regFile__DOT__reg_9;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__regFile__DOT__reg_10;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__regFile__DOT__reg_11;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__regFile__DOT__reg_12;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__regFile__DOT__reg_13;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__regFile__DOT__reg_14;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__regFile__DOT__reg_15;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__regFile__DOT__reg_16;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__regFile__DOT__reg_17;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__regFile__DOT__reg_18;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__regFile__DOT__reg_19;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__regFile__DOT__reg_20;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__regFile__DOT__reg_21;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__regFile__DOT__reg_22;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__regFile__DOT__reg_23;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__regFile__DOT__reg_24;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__regFile__DOT__reg_25;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__regFile__DOT__reg_26;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__regFile__DOT__reg_27;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__regFile__DOT__reg_28;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__regFile__DOT__reg_29;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__regFile__DOT__reg_30;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__regFile__DOT__reg_31;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__regFile__DOT___GEN_77;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__regFile__DOT___GEN_90;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__regFile__DOT___GEN_110;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__regFile__DOT___GEN_123;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__csr__DOT__medeleg_data;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__csr__DOT__mideleg_data;
        QData/*61:0*/ myCPU__DOT__datapath__DOT__csr__DOT__mtvec_base;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__csr__DOT__mscratch_data;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__csr__DOT__mepc_data;
        QData/*62:0*/ myCPU__DOT__datapath__DOT__csr__DOT__mcause_code;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__csr__DOT__mtval_data;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__csr__DOT__mcycle_data;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__csr__DOT__minstret_data;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__csr__DOT___sstatus_T;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__csr__DOT___sie_T;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__csr__DOT___sip_T;
        QData/*61:0*/ myCPU__DOT__datapath__DOT__csr__DOT__stvec_base;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__csr__DOT__sscratch_data;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__csr__DOT__sepc_data;
        QData/*62:0*/ myCPU__DOT__datapath__DOT__csr__DOT__scause_code;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__csr__DOT__stval_data;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__csr__DOT___T_163;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__csr__DOT___T_1;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__csr__DOT___T_4;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__csr__DOT___T_83;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__csr__DOT___T_96;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__csr__DOT___writeData_T_8;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__csr__DOT__writeData;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__csr__DOT__flagIntS;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__csr__DOT__flagIntM;
        QData/*62:0*/ myCPU__DOT__datapath__DOT__csr__DOT__excCause;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__csr__DOT__cause;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__csr__DOT___mcycle_data_T_1;
    };
    struct {
        QData/*63:0*/ myCPU__DOT__datapath__DOT__csr__DOT___GEN_2;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__csr__DOT___T_167;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__csr__DOT___T_169;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__csr__DOT___GEN_69;
        QData/*62:0*/ myCPU__DOT__datapath__DOT__csr__DOT___GEN_71;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__csr__DOT___GEN_72;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__csr__DOT___GEN_76;
        QData/*62:0*/ myCPU__DOT__datapath__DOT__csr__DOT___GEN_78;
        QData/*63:0*/ myCPU__DOT__datapath__DOT__csr__DOT___GEN_79;
        VlUnpacked<CData/*0:0*/, 3> __Vm_traceActivity;
    };

    // INTERNAL VARIABLES
    VmyCPU__Syms* const vlSymsp;

    // CONSTRUCTORS
    VmyCPU___024root(VmyCPU__Syms* symsp, const char* name);
    ~VmyCPU___024root();
    VL_UNCOPYABLE(VmyCPU___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);


#endif  // guard
