// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See VmyCPU.h for the primary calling header

#ifndef VERILATED_VMYCPU_DATA_CACHE_H_
#define VERILATED_VMYCPU_DATA_CACHE_H_  // guard

#include "verilated.h"

class VmyCPU__Syms;
VL_MODULE(VmyCPU_data_cache) {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(__PVT__clock,0,0);
        VL_IN8(__PVT__reset,0,0);
        VL_IN8(__PVT__io_cache_req_index,2,0);
        VL_IN8(__PVT__io_cache_req_write_index,2,0);
        VL_IN8(__PVT__io_cache_req_we,0,0);
        CData/*0:0*/ __PVT__data_mem_data_readData_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_readData_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_1_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_1_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_2_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_2_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_3_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_3_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_4_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_4_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_5_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_5_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_6_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_6_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_7_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_7_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_8_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_8_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_9_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_9_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_10_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_10_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_11_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_11_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_12_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_12_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_13_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_13_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_14_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_14_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_15_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_15_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_16_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_16_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_17_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_17_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_18_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_18_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_19_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_19_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_20_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_20_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_21_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_21_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_22_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_22_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_23_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_23_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_24_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_24_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_25_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_25_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_26_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_26_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_27_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_27_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_28_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_28_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_29_en_pipe_0;
    };
    struct {
        CData/*2:0*/ __PVT__data_mem_data_MPORT_29_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_30_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_30_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_31_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_31_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_32_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_32_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_33_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_33_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_34_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_34_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_35_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_35_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_36_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_36_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_37_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_37_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_38_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_38_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_39_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_39_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_40_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_40_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_41_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_41_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_42_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_42_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_43_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_43_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_44_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_44_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_45_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_45_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_46_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_46_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_47_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_47_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_48_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_48_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_49_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_49_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_50_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_50_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_51_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_51_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_52_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_52_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_53_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_53_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_54_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_54_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_55_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_55_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_56_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_56_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_57_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_57_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_58_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_58_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_59_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_59_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_60_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_60_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_61_en_pipe_0;
    };
    struct {
        CData/*2:0*/ __PVT__data_mem_data_MPORT_61_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_62_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_62_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_63_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_63_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_64_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_64_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_65_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_65_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_66_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_66_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_67_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_67_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_68_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_68_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_69_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_69_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_70_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_70_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_71_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_71_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_72_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_72_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_73_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_73_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_74_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_74_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_75_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_75_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_76_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_76_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_77_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_77_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_78_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_78_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_79_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_79_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_80_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_80_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_81_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_81_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_82_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_82_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_83_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_83_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_84_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_84_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_85_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_85_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_86_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_86_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_87_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_87_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_88_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_88_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_89_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_89_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_90_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_90_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_91_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_91_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_92_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_92_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_93_en_pipe_0;
    };
    struct {
        CData/*2:0*/ __PVT__data_mem_data_MPORT_93_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_94_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_94_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_95_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_95_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_96_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_96_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_97_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_97_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_98_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_98_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_99_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_99_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_100_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_100_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_101_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_101_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_102_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_102_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_103_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_103_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_104_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_104_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_105_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_105_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_106_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_106_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_107_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_107_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_108_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_108_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_109_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_109_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_110_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_110_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_111_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_111_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_112_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_112_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_113_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_113_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_114_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_114_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_115_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_115_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_116_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_116_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_117_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_117_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_118_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_118_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_119_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_119_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_120_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_120_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_121_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_121_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_122_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_122_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_123_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_123_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_124_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_124_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_125_en_pipe_0;
    };
    struct {
        CData/*2:0*/ __PVT__data_mem_data_MPORT_125_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_126_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_126_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_127_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_127_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_data_MPORT_128_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_data_MPORT_128_addr_pipe_0;
        CData/*0:0*/ __PVT__doForwardReg;
        VL_INW(__PVT__io_data_write_data,1023,0,32);
        VL_OUTW(__PVT__io_data_read_data,1023,0,32);
        VlWide<32>/*1023:0*/ __PVT__wDataReg_data;
        VlUnpacked<VlWide<32>/*1023:0*/, 8> __PVT__data_mem_data;
    };

    // INTERNAL VARIABLES
    VmyCPU__Syms* const vlSymsp;

    // CONSTRUCTORS
    VmyCPU_data_cache(VmyCPU__Syms* symsp, const char* name);
    ~VmyCPU_data_cache();
    VL_UNCOPYABLE(VmyCPU_data_cache);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);


#endif  // guard
