// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design implementation internals
// See VmyCPU.h for the primary calling header

#include "verilated.h"
#include "verilated_dpi.h"

#include "VmyCPU___024root.h"

VL_ATTR_COLD void VmyCPU___024root___eval_initial(VmyCPU___024root* vlSelf) {
    if (false && vlSelf) {}  // Prevent unused
    VmyCPU__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    VmyCPU___024root___eval_initial\n"); );
    // Body
    vlSelf->__Vclklast__TOP__clock = vlSelf->clock;
}

VL_ATTR_COLD void VmyCPU___024root___settle__TOP__0(VmyCPU___024root* vlSelf);

VL_ATTR_COLD void VmyCPU___024root___eval_settle(VmyCPU___024root* vlSelf) {
    if (false && vlSelf) {}  // Prevent unused
    VmyCPU__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    VmyCPU___024root___eval_settle\n"); );
    // Body
    VmyCPU___024root___settle__TOP__0(vlSelf);
    vlSelf->__Vm_traceActivity[1U] = 1U;
    vlSelf->__Vm_traceActivity[0U] = 1U;
}

VL_ATTR_COLD void VmyCPU___024root___final(VmyCPU___024root* vlSelf) {
    if (false && vlSelf) {}  // Prevent unused
    VmyCPU__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    VmyCPU___024root___final\n"); );
}

VL_ATTR_COLD void VmyCPU___024root___ctor_var_reset(VmyCPU___024root* vlSelf) {
    if (false && vlSelf) {}  // Prevent unused
    VmyCPU__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    VmyCPU___024root___ctor_var_reset\n"); );
    // Body
    vlSelf->clock = VL_RAND_RESET_I(1);
    vlSelf->reset = VL_RAND_RESET_I(1);
    vlSelf->io_pc_debug = VL_RAND_RESET_Q(64);
    vlSelf->io_inst = VL_RAND_RESET_I(32);
    vlSelf->io_start = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__control_io_imm_sel = VL_RAND_RESET_I(3);
    vlSelf->myCPU__DOT__control_io_csr_cmd = VL_RAND_RESET_I(3);
    vlSelf->myCPU__DOT__datapath__DOT__alu_io_A = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__alu_io_B = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__alu_io_out = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__alu_io_sum = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__brCond_io_rs1 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__brCond_io_rs2 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__regFile_io_wen = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__regFile_io_wdata = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__regFile_io_rdata_1 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__imem_pc_data = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__dmem_pc_data = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__csr_io_flush_mask = VL_RAND_RESET_I(4);
    vlSelf->myCPU__DOT__datapath__DOT__csr_io_r_op = VL_RAND_RESET_I(3);
    vlSelf->myCPU__DOT__datapath__DOT__csr_io_illegal_inst = VL_RAND_RESET_I(32);
    vlSelf->myCPU__DOT__datapath__DOT__csr_io_load_misalign = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__csr_io_store_misalign = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__csr_io_excValue = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__csr_io_trapVec = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__csr_io_trap = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__fd_pipe_reg_inst = VL_RAND_RESET_I(32);
    vlSelf->myCPU__DOT__datapath__DOT__fd_pipe_reg_pc = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__fd_pipe_reg_enable = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__de_pipe_reg_alu_op = VL_RAND_RESET_I(4);
    vlSelf->myCPU__DOT__datapath__DOT__de_pipe_reg_pc = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__de_pipe_reg_inst = VL_RAND_RESET_I(32);
    vlSelf->myCPU__DOT__datapath__DOT__de_pipe_reg_imm = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__de_pipe_reg_rs1 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__de_pipe_reg_src1_addr = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__de_pipe_reg_rs2 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__de_pipe_reg_src2_addr = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__de_pipe_reg_csr_read_data = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__de_pipe_reg_csr_write_op = VL_RAND_RESET_I(3);
    vlSelf->myCPU__DOT__datapath__DOT__de_pipe_reg_csr_write_addr = VL_RAND_RESET_I(12);
    vlSelf->myCPU__DOT__datapath__DOT__de_pipe_reg_csr_write_data = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__de_pipe_reg_dest = VL_RAND_RESET_I(5);
    vlSelf->myCPU__DOT__datapath__DOT__de_pipe_reg_A_sel = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__de_pipe_reg_B_sel = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__de_pipe_reg_pc_sel = VL_RAND_RESET_I(2);
    vlSelf->myCPU__DOT__datapath__DOT__de_pipe_reg_br_type = VL_RAND_RESET_I(3);
    vlSelf->myCPU__DOT__datapath__DOT__de_pipe_reg_wd_type = VL_RAND_RESET_I(2);
    vlSelf->myCPU__DOT__datapath__DOT__de_pipe_reg_st_type = VL_RAND_RESET_I(3);
    vlSelf->myCPU__DOT__datapath__DOT__de_pipe_reg_ld_type = VL_RAND_RESET_I(3);
    vlSelf->myCPU__DOT__datapath__DOT__de_pipe_reg_wb_sel = VL_RAND_RESET_I(2);
    vlSelf->myCPU__DOT__datapath__DOT__de_pipe_reg_wb_en = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__de_pipe_reg_enable = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__em_pipe_reg_alu_out = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__em_pipe_reg_csr_read_data = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__em_pipe_reg_csr_write_op = VL_RAND_RESET_I(3);
    vlSelf->myCPU__DOT__datapath__DOT__em_pipe_reg_csr_write_addr = VL_RAND_RESET_I(12);
    vlSelf->myCPU__DOT__datapath__DOT__em_pipe_reg_csr_write_data = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__em_pipe_reg_ld_type = VL_RAND_RESET_I(3);
    vlSelf->myCPU__DOT__datapath__DOT__em_pipe_reg_wb_sel = VL_RAND_RESET_I(2);
    vlSelf->myCPU__DOT__datapath__DOT__em_pipe_reg_wb_en = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__em_pipe_reg_dest = VL_RAND_RESET_I(5);
    vlSelf->myCPU__DOT__datapath__DOT__em_pipe_reg_pc = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__em_pipe_reg_inst = VL_RAND_RESET_I(32);
    vlSelf->myCPU__DOT__datapath__DOT__em_pipe_reg_enable = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__mw_pipe_reg_load_data = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__mw_pipe_reg_alu_out = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__mw_pipe_reg_dest = VL_RAND_RESET_I(5);
    vlSelf->myCPU__DOT__datapath__DOT__mw_pipe_reg_csr_read_data = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__mw_pipe_reg_csr_write_op = VL_RAND_RESET_I(3);
    vlSelf->myCPU__DOT__datapath__DOT__mw_pipe_reg_csr_write_addr = VL_RAND_RESET_I(12);
    vlSelf->myCPU__DOT__datapath__DOT__mw_pipe_reg_csr_write_data = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__mw_pipe_reg_wb_sel = VL_RAND_RESET_I(2);
    vlSelf->myCPU__DOT__datapath__DOT__mw_pipe_reg_wb_en = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__mw_pipe_reg_pc = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__mw_pipe_reg_inst = VL_RAND_RESET_I(32);
    vlSelf->myCPU__DOT__datapath__DOT__mw_pipe_reg_enable = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__csr_atomic_flush = VL_RAND_RESET_I(4);
    vlSelf->myCPU__DOT__datapath__DOT__brCond_taken = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__jmp_occur = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__flush_fd = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__flush_de = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__flush_em = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__flush_mw = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__started = VL_RAND_RESET_I(1);
    VL_RAND_RESET_W(65, vlSelf->myCPU__DOT__datapath__DOT__pc);
    VL_RAND_RESET_W(65, vlSelf->myCPU__DOT__datapath__DOT___next_pc_T_1);
    vlSelf->myCPU__DOT__datapath__DOT___next_pc_T_4 = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__is_kill_inst = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT___csr_op_T_2 = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT___csr_op_T_15 = VL_RAND_RESET_I(3);
    vlSelf->myCPU__DOT__datapath__DOT___de_pipe_reg_rs1_T_11 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT___de_pipe_reg_rs1_T_12 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__load_data_hazard = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT___load_data_ext_hazard_T_5 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT___load_data_ext_hazard_T_33 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT___T_2 = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT___src1_data_T_7 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT___GEN_54 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT___GEN_56 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT___GEN_58 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT___GEN_60 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__src2_data = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__A_data = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__B_data = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__st_mask = VL_RAND_RESET_I(8);
    vlSelf->myCPU__DOT__datapath__DOT__alu__DOT__shamt = VL_RAND_RESET_I(6);
    VL_RAND_RESET_W(128, vlSelf->myCPU__DOT__datapath__DOT__alu__DOT___out_T_80);
    VL_RAND_RESET_W(128, vlSelf->myCPU__DOT__datapath__DOT__alu__DOT___out_T_88);
    vlSelf->myCPU__DOT__datapath__DOT__alu__DOT__sum = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__immGen__DOT__Iimm = VL_RAND_RESET_Q(44);
    vlSelf->myCPU__DOT__datapath__DOT__immGen__DOT__Jimm = VL_RAND_RESET_Q(53);
    vlSelf->myCPU__DOT__datapath__DOT__immGen__DOT___io_out_T_5 = VL_RAND_RESET_Q(44);
    vlSelf->myCPU__DOT__datapath__DOT__immGen__DOT___io_out_T_7 = VL_RAND_RESET_Q(45);
    vlSelf->myCPU__DOT__datapath__DOT__brCond__DOT__eq = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__brCond__DOT__lt = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__brCond__DOT__ltu = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__regFile__DOT__reg_0 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__regFile__DOT__reg_1 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__regFile__DOT__reg_2 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__regFile__DOT__reg_3 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__regFile__DOT__reg_4 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__regFile__DOT__reg_5 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__regFile__DOT__reg_6 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__regFile__DOT__reg_7 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__regFile__DOT__reg_8 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__regFile__DOT__reg_9 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__regFile__DOT__reg_10 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__regFile__DOT__reg_11 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__regFile__DOT__reg_12 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__regFile__DOT__reg_13 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__regFile__DOT__reg_14 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__regFile__DOT__reg_15 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__regFile__DOT__reg_16 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__regFile__DOT__reg_17 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__regFile__DOT__reg_18 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__regFile__DOT__reg_19 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__regFile__DOT__reg_20 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__regFile__DOT__reg_21 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__regFile__DOT__reg_22 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__regFile__DOT__reg_23 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__regFile__DOT__reg_24 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__regFile__DOT__reg_25 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__regFile__DOT__reg_26 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__regFile__DOT__reg_27 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__regFile__DOT__reg_28 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__regFile__DOT__reg_29 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__regFile__DOT__reg_30 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__regFile__DOT__reg_31 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__regFile__DOT___GEN_77 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__regFile__DOT___GEN_90 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__regFile__DOT___GEN_110 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__regFile__DOT___GEN_123 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__imem__DOT__tmp_data = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__imem__DOT__delay = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__dmem__DOT__tmp_data = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__dmem__DOT__delay = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__mode = VL_RAND_RESET_I(2);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__mstatus_sum = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__mstatus_mpp = VL_RAND_RESET_I(2);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__mstatus_spp = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__mstatus_mpie = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__mstatus_spie = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__mstatus_mie = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__mstatus_sie = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__medeleg_data = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__mideleg_data = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__mie_meie = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__mie_seie = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__mie_mtie = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__mie_stie = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__mie_msie = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__mie_ssie = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__mtvec_base = VL_RAND_RESET_Q(62);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__mtvec_mode = VL_RAND_RESET_I(2);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__mscratch_data = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__mepc_data = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__mcause_int = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__mcause_code = VL_RAND_RESET_Q(63);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__mtval_data = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__mip_meip = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__mip_seip = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__mip_stip = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__mip_msip = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__mip_ssip = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__mcycle_data = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__minstret_data = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT___sstatus_T = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT___sie_T = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT___sip_T = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__stvec_base = VL_RAND_RESET_Q(62);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__stvec_mode = VL_RAND_RESET_I(2);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__sscratch_data = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__sepc_data = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__scause_int = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__scause_code = VL_RAND_RESET_Q(63);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__stval_data = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT___T_163 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT___T_1 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT___T_4 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT___T_83 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT___T_96 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__readable = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT___T_144 = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__writable = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT___instValid_T = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__valid = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__writeEn = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT___writeData_T_8 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__writeData = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__flagIntS = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__flagIntM = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__hasIntM = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__hasInt = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__handIntS = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__hasExc = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__excCause = VL_RAND_RESET_Q(63);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__handExcS = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT__cause = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT___trapVec_T = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT___mcycle_data_T_1 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT___GEN_2 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT___T_167 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT___T_169 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT___GEN_66 = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT___GEN_67 = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT___GEN_68 = VL_RAND_RESET_I(2);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT___GEN_69 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT___GEN_70 = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT___GEN_71 = VL_RAND_RESET_Q(63);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT___GEN_72 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT___GEN_74 = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT___GEN_75 = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT___GEN_76 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT___GEN_77 = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT___GEN_78 = VL_RAND_RESET_Q(63);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT___GEN_79 = VL_RAND_RESET_Q(64);
    vlSelf->myCPU__DOT__datapath__DOT__csr__DOT___GEN_81 = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__control__DOT___ctrlSignals_T_154 = VL_RAND_RESET_I(2);
    vlSelf->myCPU__DOT__control__DOT___ctrlSignals_T_169 = VL_RAND_RESET_I(2);
    vlSelf->myCPU__DOT__control__DOT___ctrlSignals_T_184 = VL_RAND_RESET_I(2);
    vlSelf->myCPU__DOT__control__DOT___ctrlSignals_T_199 = VL_RAND_RESET_I(2);
    vlSelf->myCPU__DOT__control__DOT___ctrlSignals_T_243 = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__control__DOT___ctrlSignals_T_265 = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__control__DOT___ctrlSignals_T_309 = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__control__DOT___ctrlSignals_T_326 = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__control__DOT___ctrlSignals_T_366 = VL_RAND_RESET_I(2);
    vlSelf->myCPU__DOT__control__DOT___ctrlSignals_T_381 = VL_RAND_RESET_I(2);
    vlSelf->myCPU__DOT__control__DOT___ctrlSignals_T_396 = VL_RAND_RESET_I(2);
    vlSelf->myCPU__DOT__control__DOT___ctrlSignals_T_425 = VL_RAND_RESET_I(3);
    vlSelf->myCPU__DOT__control__DOT___ctrlSignals_T_440 = VL_RAND_RESET_I(3);
    vlSelf->myCPU__DOT__control__DOT___ctrlSignals_T_455 = VL_RAND_RESET_I(3);
    vlSelf->myCPU__DOT__control__DOT___ctrlSignals_T_470 = VL_RAND_RESET_I(3);
    vlSelf->myCPU__DOT__control__DOT___ctrlSignals_T_493 = VL_RAND_RESET_I(5);
    vlSelf->myCPU__DOT__control__DOT___ctrlSignals_T_508 = VL_RAND_RESET_I(5);
    vlSelf->myCPU__DOT__control__DOT___ctrlSignals_T_523 = VL_RAND_RESET_I(5);
    vlSelf->myCPU__DOT__control__DOT___ctrlSignals_T_538 = VL_RAND_RESET_I(5);
    vlSelf->myCPU__DOT__control__DOT___ctrlSignals_T_676 = VL_RAND_RESET_I(3);
    vlSelf->myCPU__DOT__control__DOT___ctrlSignals_T_748 = VL_RAND_RESET_I(3);
    vlSelf->myCPU__DOT__control__DOT___ctrlSignals_T_765 = VL_RAND_RESET_I(2);
    vlSelf->myCPU__DOT__control__DOT___ctrlSignals_T_780 = VL_RAND_RESET_I(2);
    vlSelf->myCPU__DOT__control__DOT___ctrlSignals_T_795 = VL_RAND_RESET_I(2);
    vlSelf->myCPU__DOT__control__DOT___ctrlSignals_T_810 = VL_RAND_RESET_I(2);
    vlSelf->myCPU__DOT__control__DOT___ctrlSignals_T_821 = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__control__DOT___ctrlSignals_T_851 = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__control__DOT___ctrlSignals_T_868 = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__control__DOT___ctrlSignals_T_902 = VL_RAND_RESET_I(2);
    vlSelf->myCPU__DOT__control__DOT___ctrlSignals_T_917 = VL_RAND_RESET_I(2);
    vlSelf->myCPU__DOT__control__DOT___ctrlSignals_T_932 = VL_RAND_RESET_I(2);
    vlSelf->myCPU__DOT__control__DOT___ctrlSignals_T_947 = VL_RAND_RESET_I(2);
    vlSelf->myCPU__DOT__control__DOT___ctrlSignals_T_972 = VL_RAND_RESET_I(3);
    vlSelf->myCPU__DOT__control__DOT___ctrlSignals_T_987 = VL_RAND_RESET_I(3);
    vlSelf->myCPU__DOT__control__DOT___ctrlSignals_T_1002 = VL_RAND_RESET_I(3);
    vlSelf->myCPU__DOT__control__DOT___ctrlSignals_T_1017 = VL_RAND_RESET_I(3);
    vlSelf->myCPU__DOT__control__DOT___ctrlSignals_T_1042 = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__control__DOT___ctrlSignals_T_1059 = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__control__DOT___ctrlSignals_T_1076 = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__control__DOT___ctrlSignals_T_1109 = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__control__DOT___ctrlSignals_T_1126 = VL_RAND_RESET_I(1);
    vlSelf->myCPU__DOT__control__DOT___ctrlSignals_T_1143 = VL_RAND_RESET_I(1);
    for (int __Vi0=0; __Vi0<2; ++__Vi0) {
        vlSelf->__Vm_traceActivity[__Vi0] = VL_RAND_RESET_I(1);
    }
}
