// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See VmyCPU.h for the primary calling header

#ifndef VERILATED_VMYCPU_CACHE_H_
#define VERILATED_VMYCPU_CACHE_H_  // guard

#include "verilated.h"

class VmyCPU__Syms;
VL_MODULE(VmyCPU_Cache) {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clock,0,0);
        VL_IN8(reset,0,0);
        VL_IN8(io_cpu_request_mask,7,0);
        VL_IN8(io_cpu_request_rw,0,0);
        VL_IN8(io_cpu_request_valid,0,0);
        VL_OUT8(io_cpu_response_ready,0,0);
        VL_IN8(io_mem_io_aw_ready,0,0);
        VL_OUT8(io_mem_io_aw_valid,0,0);
        VL_OUT8(io_mem_io_aw_bits_len,7,0);
        VL_IN8(io_mem_io_w_ready,0,0);
        VL_OUT8(io_mem_io_w_valid,0,0);
        VL_OUT8(io_mem_io_w_bits_strb,7,0);
        VL_OUT8(io_mem_io_w_bits_last,0,0);
        VL_OUT8(io_mem_io_b_ready,0,0);
        VL_IN8(io_mem_io_b_valid,0,0);
        VL_IN8(io_mem_io_ar_ready,0,0);
        VL_OUT8(io_mem_io_ar_valid,0,0);
        VL_OUT8(io_mem_io_ar_bits_len,7,0);
        VL_OUT8(io_mem_io_r_ready,0,0);
        VL_IN8(io_mem_io_r_valid,0,0);
        VL_IN8(io_mem_io_r_bits_last,0,0);
        CData/*0:0*/ __PVT__tag_mem_0_io_cache_req_we;
        CData/*0:0*/ __PVT__tag_mem_0_io_tag_write_valid;
        CData/*0:0*/ __PVT__tag_mem_0_io_tag_write_dirty;
        CData/*7:0*/ __PVT__tag_mem_0_io_tag_write_visit;
        CData/*0:0*/ __PVT__tag_mem_0_io_tag_read_valid;
        CData/*0:0*/ __PVT__tag_mem_0_io_tag_read_dirty;
        CData/*7:0*/ __PVT__tag_mem_0_io_tag_read_visit;
        CData/*0:0*/ __PVT__tag_mem_1_io_cache_req_we;
        CData/*0:0*/ __PVT__tag_mem_1_io_tag_write_valid;
        CData/*0:0*/ __PVT__tag_mem_1_io_tag_write_dirty;
        CData/*7:0*/ __PVT__tag_mem_1_io_tag_write_visit;
        CData/*0:0*/ __PVT__tag_mem_1_io_tag_read_valid;
        CData/*0:0*/ __PVT__tag_mem_1_io_tag_read_dirty;
        CData/*7:0*/ __PVT__tag_mem_1_io_tag_read_visit;
        CData/*0:0*/ __PVT__tag_mem_2_io_cache_req_we;
        CData/*0:0*/ __PVT__tag_mem_2_io_tag_write_valid;
        CData/*0:0*/ __PVT__tag_mem_2_io_tag_write_dirty;
        CData/*7:0*/ __PVT__tag_mem_2_io_tag_write_visit;
        CData/*0:0*/ __PVT__tag_mem_2_io_tag_read_valid;
        CData/*0:0*/ __PVT__tag_mem_2_io_tag_read_dirty;
        CData/*7:0*/ __PVT__tag_mem_2_io_tag_read_visit;
        CData/*0:0*/ __PVT__tag_mem_3_io_cache_req_we;
        CData/*0:0*/ __PVT__tag_mem_3_io_tag_write_valid;
        CData/*0:0*/ __PVT__tag_mem_3_io_tag_write_dirty;
        CData/*7:0*/ __PVT__tag_mem_3_io_tag_write_visit;
        CData/*0:0*/ __PVT__tag_mem_3_io_tag_read_valid;
        CData/*0:0*/ __PVT__tag_mem_3_io_tag_read_dirty;
        CData/*7:0*/ __PVT__tag_mem_3_io_tag_read_visit;
        CData/*0:0*/ __PVT__data_mem_0_io_cache_req_we;
        CData/*0:0*/ __PVT__data_mem_1_io_cache_req_we;
        CData/*0:0*/ __PVT__data_mem_2_io_cache_req_we;
        CData/*0:0*/ __PVT__data_mem_3_io_cache_req_we;
        CData/*3:0*/ __PVT__cache_state;
        CData/*3:0*/ __PVT__index;
        CData/*0:0*/ __PVT__fill_block_en;
        CData/*3:0*/ __PVT___GEN_0;
        CData/*0:0*/ __PVT__last;
        CData/*1:0*/ __PVT__replace;
        CData/*7:0*/ __PVT__cpu_request_mask;
        CData/*0:0*/ __PVT__cpu_request_rw;
        CData/*0:0*/ __PVT__is_match_0;
        CData/*0:0*/ __PVT__is_match_1;
        CData/*0:0*/ __PVT__is_match_2;
    };
    struct {
        CData/*0:0*/ __PVT__is_match_3;
        CData/*7:0*/ __PVT___part_0_T_22;
        CData/*7:0*/ __PVT__visit_1;
        CData/*7:0*/ __PVT__visit_0;
        CData/*7:0*/ __PVT__visit_3;
        CData/*7:0*/ __PVT__visit_2;
        CData/*0:0*/ __PVT__compare_2_3;
        CData/*0:0*/ __PVT__compare_1_0;
        CData/*0:0*/ __PVT__max_01_or_23;
        CData/*1:0*/ __PVT__max;
        CData/*3:0*/ __PVT___GEN_1593;
        CData/*1:0*/ __PVT___GEN_1663;
        CData/*3:0*/ __PVT___GEN_1671;
        CData/*0:0*/ __PVT__tag_mem_0__DOT__tag_mem_0_valid;
        CData/*0:0*/ __PVT__tag_mem_0__DOT__tag_mem_0_dirty;
        CData/*7:0*/ __PVT__tag_mem_0__DOT__tag_mem_0_visit;
        CData/*0:0*/ __PVT__tag_mem_0__DOT__tag_mem_1_valid;
        CData/*0:0*/ __PVT__tag_mem_0__DOT__tag_mem_1_dirty;
        CData/*7:0*/ __PVT__tag_mem_0__DOT__tag_mem_1_visit;
        CData/*0:0*/ __PVT__tag_mem_0__DOT__tag_mem_2_valid;
        CData/*0:0*/ __PVT__tag_mem_0__DOT__tag_mem_2_dirty;
        CData/*7:0*/ __PVT__tag_mem_0__DOT__tag_mem_2_visit;
        CData/*0:0*/ __PVT__tag_mem_0__DOT__tag_mem_3_valid;
        CData/*0:0*/ __PVT__tag_mem_0__DOT__tag_mem_3_dirty;
        CData/*7:0*/ __PVT__tag_mem_0__DOT__tag_mem_3_visit;
        CData/*0:0*/ __PVT__tag_mem_0__DOT__tag_mem_4_valid;
        CData/*0:0*/ __PVT__tag_mem_0__DOT__tag_mem_4_dirty;
        CData/*7:0*/ __PVT__tag_mem_0__DOT__tag_mem_4_visit;
        CData/*0:0*/ __PVT__tag_mem_0__DOT__tag_mem_5_valid;
        CData/*0:0*/ __PVT__tag_mem_0__DOT__tag_mem_5_dirty;
        CData/*7:0*/ __PVT__tag_mem_0__DOT__tag_mem_5_visit;
        CData/*0:0*/ __PVT__tag_mem_0__DOT__tag_mem_6_valid;
        CData/*0:0*/ __PVT__tag_mem_0__DOT__tag_mem_6_dirty;
        CData/*7:0*/ __PVT__tag_mem_0__DOT__tag_mem_6_visit;
        CData/*0:0*/ __PVT__tag_mem_0__DOT__tag_mem_7_valid;
        CData/*0:0*/ __PVT__tag_mem_0__DOT__tag_mem_7_dirty;
        CData/*7:0*/ __PVT__tag_mem_0__DOT__tag_mem_7_visit;
        CData/*0:0*/ __PVT__tag_mem_1__DOT__tag_mem_0_valid;
        CData/*0:0*/ __PVT__tag_mem_1__DOT__tag_mem_0_dirty;
        CData/*7:0*/ __PVT__tag_mem_1__DOT__tag_mem_0_visit;
        CData/*0:0*/ __PVT__tag_mem_1__DOT__tag_mem_1_valid;
        CData/*0:0*/ __PVT__tag_mem_1__DOT__tag_mem_1_dirty;
        CData/*7:0*/ __PVT__tag_mem_1__DOT__tag_mem_1_visit;
        CData/*0:0*/ __PVT__tag_mem_1__DOT__tag_mem_2_valid;
        CData/*0:0*/ __PVT__tag_mem_1__DOT__tag_mem_2_dirty;
        CData/*7:0*/ __PVT__tag_mem_1__DOT__tag_mem_2_visit;
        CData/*0:0*/ __PVT__tag_mem_1__DOT__tag_mem_3_valid;
        CData/*0:0*/ __PVT__tag_mem_1__DOT__tag_mem_3_dirty;
        CData/*7:0*/ __PVT__tag_mem_1__DOT__tag_mem_3_visit;
        CData/*0:0*/ __PVT__tag_mem_1__DOT__tag_mem_4_valid;
        CData/*0:0*/ __PVT__tag_mem_1__DOT__tag_mem_4_dirty;
        CData/*7:0*/ __PVT__tag_mem_1__DOT__tag_mem_4_visit;
        CData/*0:0*/ __PVT__tag_mem_1__DOT__tag_mem_5_valid;
        CData/*0:0*/ __PVT__tag_mem_1__DOT__tag_mem_5_dirty;
        CData/*7:0*/ __PVT__tag_mem_1__DOT__tag_mem_5_visit;
        CData/*0:0*/ __PVT__tag_mem_1__DOT__tag_mem_6_valid;
        CData/*0:0*/ __PVT__tag_mem_1__DOT__tag_mem_6_dirty;
        CData/*7:0*/ __PVT__tag_mem_1__DOT__tag_mem_6_visit;
        CData/*0:0*/ __PVT__tag_mem_1__DOT__tag_mem_7_valid;
        CData/*0:0*/ __PVT__tag_mem_1__DOT__tag_mem_7_dirty;
        CData/*7:0*/ __PVT__tag_mem_1__DOT__tag_mem_7_visit;
        CData/*0:0*/ __PVT__tag_mem_2__DOT__tag_mem_0_valid;
        CData/*0:0*/ __PVT__tag_mem_2__DOT__tag_mem_0_dirty;
        CData/*7:0*/ __PVT__tag_mem_2__DOT__tag_mem_0_visit;
    };
    struct {
        CData/*0:0*/ __PVT__tag_mem_2__DOT__tag_mem_1_valid;
        CData/*0:0*/ __PVT__tag_mem_2__DOT__tag_mem_1_dirty;
        CData/*7:0*/ __PVT__tag_mem_2__DOT__tag_mem_1_visit;
        CData/*0:0*/ __PVT__tag_mem_2__DOT__tag_mem_2_valid;
        CData/*0:0*/ __PVT__tag_mem_2__DOT__tag_mem_2_dirty;
        CData/*7:0*/ __PVT__tag_mem_2__DOT__tag_mem_2_visit;
        CData/*0:0*/ __PVT__tag_mem_2__DOT__tag_mem_3_valid;
        CData/*0:0*/ __PVT__tag_mem_2__DOT__tag_mem_3_dirty;
        CData/*7:0*/ __PVT__tag_mem_2__DOT__tag_mem_3_visit;
        CData/*0:0*/ __PVT__tag_mem_2__DOT__tag_mem_4_valid;
        CData/*0:0*/ __PVT__tag_mem_2__DOT__tag_mem_4_dirty;
        CData/*7:0*/ __PVT__tag_mem_2__DOT__tag_mem_4_visit;
        CData/*0:0*/ __PVT__tag_mem_2__DOT__tag_mem_5_valid;
        CData/*0:0*/ __PVT__tag_mem_2__DOT__tag_mem_5_dirty;
        CData/*7:0*/ __PVT__tag_mem_2__DOT__tag_mem_5_visit;
        CData/*0:0*/ __PVT__tag_mem_2__DOT__tag_mem_6_valid;
        CData/*0:0*/ __PVT__tag_mem_2__DOT__tag_mem_6_dirty;
        CData/*7:0*/ __PVT__tag_mem_2__DOT__tag_mem_6_visit;
        CData/*0:0*/ __PVT__tag_mem_2__DOT__tag_mem_7_valid;
        CData/*0:0*/ __PVT__tag_mem_2__DOT__tag_mem_7_dirty;
        CData/*7:0*/ __PVT__tag_mem_2__DOT__tag_mem_7_visit;
        CData/*0:0*/ __PVT__tag_mem_3__DOT__tag_mem_0_valid;
        CData/*0:0*/ __PVT__tag_mem_3__DOT__tag_mem_0_dirty;
        CData/*7:0*/ __PVT__tag_mem_3__DOT__tag_mem_0_visit;
        CData/*0:0*/ __PVT__tag_mem_3__DOT__tag_mem_1_valid;
        CData/*0:0*/ __PVT__tag_mem_3__DOT__tag_mem_1_dirty;
        CData/*7:0*/ __PVT__tag_mem_3__DOT__tag_mem_1_visit;
        CData/*0:0*/ __PVT__tag_mem_3__DOT__tag_mem_2_valid;
        CData/*0:0*/ __PVT__tag_mem_3__DOT__tag_mem_2_dirty;
        CData/*7:0*/ __PVT__tag_mem_3__DOT__tag_mem_2_visit;
        CData/*0:0*/ __PVT__tag_mem_3__DOT__tag_mem_3_valid;
        CData/*0:0*/ __PVT__tag_mem_3__DOT__tag_mem_3_dirty;
        CData/*7:0*/ __PVT__tag_mem_3__DOT__tag_mem_3_visit;
        CData/*0:0*/ __PVT__tag_mem_3__DOT__tag_mem_4_valid;
        CData/*0:0*/ __PVT__tag_mem_3__DOT__tag_mem_4_dirty;
        CData/*7:0*/ __PVT__tag_mem_3__DOT__tag_mem_4_visit;
        CData/*0:0*/ __PVT__tag_mem_3__DOT__tag_mem_5_valid;
        CData/*0:0*/ __PVT__tag_mem_3__DOT__tag_mem_5_dirty;
        CData/*7:0*/ __PVT__tag_mem_3__DOT__tag_mem_5_visit;
        CData/*0:0*/ __PVT__tag_mem_3__DOT__tag_mem_6_valid;
        CData/*0:0*/ __PVT__tag_mem_3__DOT__tag_mem_6_dirty;
        CData/*7:0*/ __PVT__tag_mem_3__DOT__tag_mem_6_visit;
        CData/*0:0*/ __PVT__tag_mem_3__DOT__tag_mem_7_valid;
        CData/*0:0*/ __PVT__tag_mem_3__DOT__tag_mem_7_dirty;
        CData/*7:0*/ __PVT__tag_mem_3__DOT__tag_mem_7_visit;
        CData/*0:0*/ __PVT__data_mem_0__DOT__data_mem_data_readData_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_0__DOT__data_mem_data_readData_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_0__DOT__doForwardReg;
        CData/*0:0*/ __PVT__data_mem_1__DOT__data_mem_data_readData_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_1__DOT__data_mem_data_readData_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_1__DOT__doForwardReg;
        CData/*0:0*/ __PVT__data_mem_2__DOT__data_mem_data_readData_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_2__DOT__data_mem_data_readData_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_2__DOT__doForwardReg;
        CData/*0:0*/ __PVT__data_mem_3__DOT__data_mem_data_readData_en_pipe_0;
        CData/*2:0*/ __PVT__data_mem_3__DOT__data_mem_data_readData_addr_pipe_0;
        CData/*0:0*/ __PVT__data_mem_3__DOT__doForwardReg;
        SData/*15:0*/ __PVT___part_1_T_22;
        VL_IN(io_cpu_request_addr,31,0);
        VL_OUT(io_mem_io_aw_bits_addr,31,0);
        VL_OUT(io_mem_io_ar_bits_addr,31,0);
        IData/*21:0*/ __PVT__tag_mem_0_io_tag_write_tag;
        IData/*21:0*/ __PVT__tag_mem_0_io_tag_read_tag;
        IData/*21:0*/ __PVT__tag_mem_1_io_tag_write_tag;
    };
    struct {
        IData/*21:0*/ __PVT__tag_mem_1_io_tag_read_tag;
        IData/*21:0*/ __PVT__tag_mem_2_io_tag_write_tag;
        IData/*21:0*/ __PVT__tag_mem_2_io_tag_read_tag;
        IData/*21:0*/ __PVT__tag_mem_3_io_tag_write_tag;
        IData/*21:0*/ __PVT__tag_mem_3_io_tag_read_tag;
        VlWide<32>/*1023:0*/ __PVT__data_mem_0_io_data_write_data;
        VlWide<32>/*1023:0*/ __PVT__data_mem_0_io_data_read_data;
        VlWide<32>/*1023:0*/ __PVT__data_mem_1_io_data_write_data;
        VlWide<32>/*1023:0*/ __PVT__data_mem_1_io_data_read_data;
        VlWide<32>/*1023:0*/ __PVT__data_mem_2_io_data_write_data;
        VlWide<32>/*1023:0*/ __PVT__data_mem_2_io_data_read_data;
        VlWide<32>/*1023:0*/ __PVT__data_mem_3_io_data_write_data;
        VlWide<32>/*1023:0*/ __PVT__data_mem_3_io_data_read_data;
        IData/*31:0*/ __PVT__refill_addr;
        IData/*31:0*/ __PVT__writeback_addr;
        IData/*31:0*/ __PVT__cpu_request_addr_reg;
        VlWide<32>/*1023:0*/ __PVT__response_data;
        IData/*23:0*/ __PVT___part_2_T_22;
        IData/*31:0*/ __PVT___part_3_T_22;
        IData/*31:0*/ __PVT___GEN_1664;
        IData/*31:0*/ __PVT___GEN_1665;
        IData/*21:0*/ __PVT__tag_mem_0__DOT__tag_mem_0_tag;
        IData/*21:0*/ __PVT__tag_mem_0__DOT__tag_mem_1_tag;
        IData/*21:0*/ __PVT__tag_mem_0__DOT__tag_mem_2_tag;
        IData/*21:0*/ __PVT__tag_mem_0__DOT__tag_mem_3_tag;
        IData/*21:0*/ __PVT__tag_mem_0__DOT__tag_mem_4_tag;
        IData/*21:0*/ __PVT__tag_mem_0__DOT__tag_mem_5_tag;
        IData/*21:0*/ __PVT__tag_mem_0__DOT__tag_mem_6_tag;
        IData/*21:0*/ __PVT__tag_mem_0__DOT__tag_mem_7_tag;
        IData/*21:0*/ __PVT__tag_mem_1__DOT__tag_mem_0_tag;
        IData/*21:0*/ __PVT__tag_mem_1__DOT__tag_mem_1_tag;
        IData/*21:0*/ __PVT__tag_mem_1__DOT__tag_mem_2_tag;
        IData/*21:0*/ __PVT__tag_mem_1__DOT__tag_mem_3_tag;
        IData/*21:0*/ __PVT__tag_mem_1__DOT__tag_mem_4_tag;
        IData/*21:0*/ __PVT__tag_mem_1__DOT__tag_mem_5_tag;
        IData/*21:0*/ __PVT__tag_mem_1__DOT__tag_mem_6_tag;
        IData/*21:0*/ __PVT__tag_mem_1__DOT__tag_mem_7_tag;
        IData/*21:0*/ __PVT__tag_mem_2__DOT__tag_mem_0_tag;
        IData/*21:0*/ __PVT__tag_mem_2__DOT__tag_mem_1_tag;
        IData/*21:0*/ __PVT__tag_mem_2__DOT__tag_mem_2_tag;
        IData/*21:0*/ __PVT__tag_mem_2__DOT__tag_mem_3_tag;
        IData/*21:0*/ __PVT__tag_mem_2__DOT__tag_mem_4_tag;
        IData/*21:0*/ __PVT__tag_mem_2__DOT__tag_mem_5_tag;
        IData/*21:0*/ __PVT__tag_mem_2__DOT__tag_mem_6_tag;
        IData/*21:0*/ __PVT__tag_mem_2__DOT__tag_mem_7_tag;
        IData/*21:0*/ __PVT__tag_mem_3__DOT__tag_mem_0_tag;
        IData/*21:0*/ __PVT__tag_mem_3__DOT__tag_mem_1_tag;
        IData/*21:0*/ __PVT__tag_mem_3__DOT__tag_mem_2_tag;
        IData/*21:0*/ __PVT__tag_mem_3__DOT__tag_mem_3_tag;
        IData/*21:0*/ __PVT__tag_mem_3__DOT__tag_mem_4_tag;
        IData/*21:0*/ __PVT__tag_mem_3__DOT__tag_mem_5_tag;
        IData/*21:0*/ __PVT__tag_mem_3__DOT__tag_mem_6_tag;
        IData/*21:0*/ __PVT__tag_mem_3__DOT__tag_mem_7_tag;
        VlWide<32>/*1023:0*/ __PVT__data_mem_0__DOT__wDataReg_data;
        VlWide<32>/*1023:0*/ __PVT__data_mem_1__DOT__wDataReg_data;
        VlWide<32>/*1023:0*/ __PVT__data_mem_2__DOT__wDataReg_data;
        VlWide<32>/*1023:0*/ __PVT__data_mem_3__DOT__wDataReg_data;
        VL_IN64(io_cpu_request_data,63,0);
        VL_OUT64(io_cpu_response_data,63,0);
        VL_OUT64(io_mem_io_w_bits_data,63,0);
        VL_IN64(io_mem_io_r_bits_data,63,0);
        QData/*63:0*/ __PVT__cpu_request_data;
        QData/*63:0*/ __PVT___io_cpu_response_data_T_70;
        QData/*39:0*/ __PVT___part_4_T_22;
    };
    struct {
        QData/*47:0*/ __PVT___part_5_T_22;
        QData/*55:0*/ __PVT___part_6_T_22;
        QData/*63:0*/ __PVT___part_7_T_22;
        QData/*63:0*/ __PVT__result;
        QData/*63:0*/ __PVT__cache_data_1;
        QData/*63:0*/ __PVT__cache_data_0;
        QData/*63:0*/ __PVT__cache_data_3;
        QData/*63:0*/ __PVT__cache_data_2;
        QData/*63:0*/ __PVT__cache_data_5;
        QData/*63:0*/ __PVT__cache_data_4;
        QData/*63:0*/ __PVT__cache_data_7;
        QData/*63:0*/ __PVT__cache_data_6;
        QData/*63:0*/ __PVT__cache_data_9;
        QData/*63:0*/ __PVT__cache_data_8;
        QData/*63:0*/ __PVT__cache_data_11;
        QData/*63:0*/ __PVT__cache_data_10;
        QData/*63:0*/ __PVT__cache_data_13;
        QData/*63:0*/ __PVT__cache_data_12;
        QData/*63:0*/ __PVT__cache_data_15;
        QData/*63:0*/ __PVT__cache_data_14;
        QData/*63:0*/ __PVT___GEN_1143;
        VlUnpacked<VlWide<32>/*1023:0*/, 8> __PVT__data_mem_0__DOT__data_mem_data;
        VlUnpacked<VlWide<32>/*1023:0*/, 8> __PVT__data_mem_1__DOT__data_mem_data;
        VlUnpacked<VlWide<32>/*1023:0*/, 8> __PVT__data_mem_2__DOT__data_mem_data;
        VlUnpacked<VlWide<32>/*1023:0*/, 8> __PVT__data_mem_3__DOT__data_mem_data;
    };

    // INTERNAL VARIABLES
    VmyCPU__Syms* const vlSymsp;

    // CONSTRUCTORS
    VmyCPU_Cache(VmyCPU__Syms* symsp, const char* name);
    ~VmyCPU_Cache();
    VL_UNCOPYABLE(VmyCPU_Cache);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);


#endif  // guard
