# files of NVBoard
# 添加头文件和源文件路径
NVBOARD_SRC = $(NVBOARD_HOME)/src
NVBOARD_SRCS := $(shell find $(NVBOARD_SRC) -name "*.cpp")
NVBOARD_INC = $(NVBOARD_HOME)/include
INC_PATH += $(NVBOARD_INC)


#build放在主目录下
#notdir 用于去除文件的绝对路径
#basename 用于取出文件从右到左的一个"."前面的字符串
#addsuffix 添加后缀
#addprefix 添加前缀
#综上下面的话的意思就是将要生存的object文件名
NVBOARD_BUILD_DIR = $(NVBOARD_HOME)/build
NVBOARD_OBJS := $(addprefix $(NVBOARD_BUILD_DIR)/, $(addsuffix .o, $(basename $(notdir $(NVBOARD_SRCS)))))

# The archive of NVBoard
NVBOARD_ARCHIVE = $(NVBOARD_BUILD_DIR)/nvboard.a
CXXFLAGS += -MMD -O3

#生存object文件 
$(NVBOARD_BUILD_DIR)/%.o: $(NVBOARD_SRC)/%.cpp
	@echo + CXX "->" NVBOARD_HOME/$(shell realpath $< --relative-to $(NVBOARD_HOME))
	@mkdir -p $(dir $@)
	@$(CXX) $(CXXFLAGS) -I$(NVBOARD_INC) -c -o $@ $<

# Build the archive of NVBoard
$(NVBOARD_ARCHIVE): $(NVBOARD_OBJS)
	@echo + AR "->" $(shell realpath $@ --relative-to $(NVBOARD_HOME))
	@ar rcs $(NVBOARD_ARCHIVE) $(NVBOARD_OBJS)

# Rule (`#include` dependencies): paste in `.d` files generated by gcc on `-MMD`
-include $(NVBOARD_OBJS:.o=.d)

.PHONY: nvboard-archive nvboard-clean

nvboard-archive: $(NVBOARD_ARCHIVE)

nvboard-clean:
	rm -rf $(NVBOARD_BUILD_DIR)
